### ISSUE TITLE
Is this project still running?

### ISSUE THREAD

**Issue by icarooliv** [nileorg/instance-api#1]
Hey! First of all, sorry if this is not the right place to open this type of issue :sweat_smile: 

Found this project at [open-source-ideas](https://github.com/open-source-ideas/open-source-ideas/issues/78) and tought pretty cool!! 

I never contributed to any open source idea (besides my personal and college's projects), but I feels that I'm prepared to give a shot! 

So, if this project is still running, I will feel very happy to help contribute!

I'm more comfortable with NodeJS, backend, CI/CD and stuff like that but I'm learning Vue aswell and I can give a hand on that.

Cheers from Brazil,
Ícaro

**Comment by marcocastignoli** [comment]
Hey Icaro, join our Discord! https://discord.gg/je27JSc
